// src/components/footer.tsx
'use client';

import Link from 'next/link';

export default function Footer() {
  return (
    <>
      <div style={{ marginBottom: '8rem' }} />
      <hr />
      <div style={{ marginTop: '4rem' }} />
      <footer>
        &copy; 2025 Florian Frauenfelder // <Link href='/'>Home</Link> //{' '}
        <Link href='/contact/'>Contact form</Link> //{' '}
        <Link href='/legal/'>
          Legal: Contact, Copyright, Disclaimer, Privacy policy
        </Link>
      </footer>
    </>
  );
}

// src/lib/Footer.svelte
<div style="margin-bottom: 8rem;"></div>
<hr />
<div style="margin-top: 4rem;"></div>
<footer>
  &copy;&nbsp;2025&ndash;2026 Florian Frauenfelder // <a href="/">Home</a> //
  <a href="/contact/">Contact form</a>
  //
  <a href="/legal/">Legal: Contact, Copyright, Disclaimer, Privacy policy</a>
</footer>
