// components/navBar.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';

const matchPath = (current: string, link: string): 'active' | '' =>
  link && (current === link || (current.startsWith(link) && link.length >= 3))
    ? 'active'
    : '';

export default function NavBar() {
  useEffect(() => {
    const handleScroll = () => {
      const nav = document.querySelector('nav');
      if (nav) {
        // Add sticky class to navbar when on top of screen
        if (nav.getBoundingClientRect().top <= 0) nav.classList.add('sticky');
        else nav.classList.remove('sticky');
      }
    };
    // Correctly apply stickyness after reload
    handleScroll();
    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  const path = usePathname();
  const navRef = useRef<HTMLElement | null>(null);
  const [isOpen, setIsOpen] = useState(false);
  useEffect(() => {
    // Close navBar after route change
    setIsOpen(false);
    navRef?.current?.classList.remove('responsive');
  }, [path])

  return (
    <nav ref={navRef}>
      <Link href='/' className={matchPath(path, '/')}>
        Home
      </Link>
      {/* <div class='dropdown'>
        <button class='dropbtn'>Teaching Assistant
          <i class='fa fa-caret-down'></i>
        </button>
        <div class='dropdown-content'>
          <a href='/ta/linalg/'>Lineare Algebra II</a>
          <a href='/ta/informatik/'>Informatik</a>
          <a href='/ta/'><i>Overview</i></a>
        </div>
      </div> */}
      <Link href='/ta/' className={matchPath(path, '/ta/')}>
        Teaching Assistant
      </Link>
      <Link href='/coding/' className={matchPath(path, '/coding/')}>
        Hobby Coder
      </Link>
      <Link href='/astro/' className={matchPath(path, '/astro/')}>
        Hobby Astronomer
      </Link>
      <Link id='legal' href='/legal/' className={matchPath(path, '/legal/')}>
        Legal
      </Link>
      <button
        className='icon'
        onClick={() => {
          if (navRef.current) {
            navRef.current.classList.toggle('responsive');
            setIsOpen(!isOpen);
          }
        }}
      >
        {isOpen ? '\u25b2' : '\u25bc'}
      </button>
    </nav>
  );
}

// src/lib/NavBar.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { navItems } from './navigation';

  let nav: HTMLElement;
  let isOpen = $state(false);

  function onscroll() {
    if (!nav) return;
    if (nav.getBoundingClientRect().top <= 0) nav.classList.add('sticky');
    else nav.classList.remove('sticky');
  }

  $effect(() => {
    if (nav) onscroll();
  });
</script>

<svelte:window {onscroll} />

<nav bind:this={nav}>
  {#each navItems.slice(1) as { href, name, id }}
    <a
      {id}
      {href}
      class={page.url.pathname === href || (page.url.pathname.startsWith(href) && href.length >= 3)
        ? 'active'
        : ''}
      onclick={() => {
        isOpen = false;
        nav.classList.remove('responsive');
      }}
    >
      {name}
    </a>
  {/each}
  <button
    class="icon"
    onclick={() => {
      isOpen = !isOpen;
      nav.classList.toggle('responsive');
    }}
  >
    {isOpen ? '\u25b2' : '\u25bc'}
  </button>
</nav>
