// src/lib/Title.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { findNavItem, navItems } from './navigation';

  let active = $derived(findNavItem(page.url.pathname) ?? navItems[0]);
  let titles = $derived(active.title.match(/^Florian(\b.*)/));
</script>

<h1>
  {#if titles}
    <a href="/" class="normal">Florian</a>{titles[1]}
  {:else}
    {active.title}
  {/if}
</h1>

// components/title.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { getAttr } from './routing';

export default function Title() {
  const title = getAttr(usePathname(), 'title');
  const titles = title!.match(/^Florian(\b.*)/);
  return (
    <h1>
      {titles ? (
        <>
          <Link href='/' className='normal'>
            Florian
          </Link>
          {titles[1]}
        </>
      ) : (
        title
      )}
    </h1>
  );
}
