// src/routes/ta/+page.svelte
<h2>Teaching Assistant positions</h2>

<p>
  A list of all my teaching assistant positions with links to my material and the course
  information, sorted by semester:
</p>

<ul>
  <li>
    <em>[Autumn 2025]</em>
    <a href="complex-analysis/">Material</a> for Funktionentheorie for BSc D-MATH, D-PHYS (<a
      target="_blank"
      href="https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?semkez=2025W&lerneinheitId=193482"
    >
      401-2303-00L
    </a>)
  </li>
  <li>
    <em>[Spring 2025]</em>
    <a href="linear-algebra-ii/">Material</a> for Lineare Algebra II for BSc D-MATH, D-PHYS (<a
      target="_blank"
      href="https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?semkez=2025S&lerneinheitId=188649"
    >
      401-1152-02L
    </a>)
  </li>
  <li>
    <em>[Autumn 2024]</em>
    <a href="computer-science/">Material</a> for Informatik for IFMP (BSc D-MATH, D-PHYS) (<a
      target="_blank"
      href="https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?semkez=2024W&lerneinheitId=182354"
    >
      252-0847-00L
    </a>)
  </li>
</ul>

// app/ta/page.tsx
import { getRouteMetadata } from '@/components/routing';
import Link from 'next/link';

export const metadata = getRouteMetadata('/ta/');

export default function TA() {
  return (
    <>
      <h2>Teaching Assistant positions</h2>
      <ul>
        <li>
          <em>[1/2025]</em> In spring 2025, I am a teaching assistant for
          Lineare Algebra II for BSc D-MATH, D-PHYS, course{' '}
          <Link
            target='_blank'
            href='https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?semkez=2025S&lerneinheitId=188649'
          >
            401-1152-02L
          </Link>
          . All the material is available <Link href='linalg/'>here</Link>.
        </li>
        <li>
          <em>[2/2024]</em> In autumn 2024, I was a teaching assistant for
          Informatik for IFMP (BSc D-MATH, D-PHYS), course{' '}
          <Link
            target='_blank'
            href='https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?semkez=2024W&lerneinheitId=182354'
          >
            252-0847-00L
          </Link>
          . All the material is available <Link href='informatik/'>here</Link>.
        </li>
      </ul>
    </>
  );
}
